apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emk-search-service-data
  namespace: search-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
